#!/usr/bin/env node

import { spawnSync } from "node:child_process";
import fs from "node:fs/promises";
import path from "node:path";

function parseArgs(argv) {
  const args = {
    includeE2E: true,
    includeLiveQuality: false,
    baseUrl: "http://localhost:5050",
    outputDir: ".ci/pilot"
  };
  for (let i = 0; i < argv.length; i += 1) {
    const token = argv[i];
    if (token === "--no-e2e") args.includeE2E = false;
    if (token === "--with-live-quality") args.includeLiveQuality = true;
    if (token === "--base-url") {
      args.baseUrl = argv[i + 1] || args.baseUrl;
      i += 1;
      continue;
    }
    if (token === "--output-dir") {
      args.outputDir = argv[i + 1] || args.outputDir;
      i += 1;
      continue;
    }
  }
  return args;
}

function runStep(command) {
  const startedAt = new Date().toISOString();
  const startMs = Date.now();
  // eslint-disable-next-line no-console
  console.log(`\n[check] ${command.name}`);
  const result = spawnSync(command.cmd, command.args, {
    stdio: "inherit",
    shell: false
  });
  const durationMs = Math.max(0, Date.now() - startMs);
  const status = result.status === 0 ? "pass" : "fail";
  return {
    name: command.name,
    command: [command.cmd, ...command.args].join(" "),
    startedAt,
    finishedAt: new Date().toISOString(),
    durationMs,
    status,
    exitCode: result.status ?? 1
  };
}

function toMarkdown(report) {
  const lines = [];
  lines.push("# Pre-Pilot Checklist Report");
  lines.push("");
  lines.push(`Generated: ${report.generatedAt}`);
  lines.push(`Status: ${report.pass ? "PASS" : "FAIL"}`);
  lines.push("");
  lines.push("| Step | Status | Duration (s) | Exit |");
  lines.push("| --- | --- | ---: | ---: |");
  for (const step of report.steps) {
    lines.push(`| ${step.name} | ${step.status.toUpperCase()} | ${(step.durationMs / 1000).toFixed(1)} | ${step.exitCode} |`);
  }
  lines.push("");
  if (!report.pass) {
    lines.push("## Failure");
    lines.push("");
    lines.push(`- Failed at: ${report.failedStep ?? "unknown"}`);
    lines.push("");
  }
  lines.push("## Notes");
  lines.push("");
  lines.push("- This report is generated by `scripts/run_prepilot_checklist.mjs`.");
  lines.push("- Use this as the pilot go/no-go gate artifact.");
  lines.push("");
  return `${lines.join("\n")}\n`;
}

async function main() {
  const args = parseArgs(process.argv.slice(2));
  const commands = [
    { name: "typecheck", cmd: "npm", args: ["run", "typecheck"] },
    { name: "lint", cmd: "npm", args: ["run", "lint"] },
    { name: "unit-tests", cmd: "npm", args: ["test"] },
    { name: "coverage", cmd: "npm", args: ["run", "test:coverage"] },
    { name: "build", cmd: "npm", args: ["run", "build"] }
  ];

  if (args.includeE2E) {
    commands.push({
      name: "e2e-v2-gate-journey",
      cmd: "npm",
      args: ["--workspace", "web", "run", "test:e2e", "--", "-g", "v2 workflow run pauses at gates and resumes to final deck spec artifacts"]
    });
  }

  if (args.includeLiveQuality) {
    commands.push({
      name: "live-v2-quality-harness",
      cmd: "node",
      args: [
        "scripts/v2_pilot_quality_harness.mjs",
        "--base-url",
        args.baseUrl,
        "--enforce-slo",
        "--min-qa-accept-rate",
        "0.66",
        "--min-med-pass-rate",
        "0.66",
        "--min-story-score",
        "3.2",
        "--min-twist-score",
        "3.0",
        "--min-clarity-score",
        "3.4",
        "--min-story-forward-ratio",
        "0.7",
        "--min-packaging-completeness",
        "1",
        "--min-main-render-coverage",
        "0.95",
        "--min-clue-payoff-coverage",
        "1",
        "--min-render-plan-marker-pass-rate",
        "1",
        "--max-placeholder-run-rate",
        "0.15",
        "--max-fallback-run-rate",
        "0.05",
        "--max-error-rate",
        "0.2",
        "--max-timeout-rate",
        "0.1"
      ]
    });
  }

  const steps = [];
  let failedStep = null;
  for (const command of commands) {
    const result = runStep(command);
    steps.push(result);
    if (result.status !== "pass") {
      failedStep = command.name;
      break;
    }
  }

  const report = {
    generatedAt: new Date().toISOString(),
    pass: failedStep === null,
    failedStep,
    options: args,
    steps
  };

  await fs.mkdir(args.outputDir, { recursive: true });
  const outJson = path.join(args.outputDir, "prepilot-checklist-latest.json");
  const outMd = path.join(args.outputDir, "prepilot-checklist-latest.md");
  await fs.writeFile(outJson, `${JSON.stringify(report, null, 2)}\n`, "utf8");
  await fs.writeFile(outMd, toMarkdown(report), "utf8");

  // eslint-disable-next-line no-console
  console.log(`Wrote ${outJson}`);
  // eslint-disable-next-line no-console
  console.log(`Wrote ${outMd}`);

  if (!report.pass) {
    throw new Error(`Pre-pilot checklist failed at step: ${failedStep}`);
  }
}

main().catch((error) => {
  const message = error instanceof Error ? error.message : String(error);
  // eslint-disable-next-line no-console
  console.error(`run_prepilot_checklist failed: ${message}`);
  process.exitCode = 1;
});
